# Generated by Django 5.0.4 on 2024-05-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
