# Generated by Django 5.0.4 on 2024-05-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create',
        ),
    ]
