# Generated by Django 5.0.4 on 2024-05-12 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 0, 0)),
            preserve_default=False,
        ),
    ]
