# Generated by Django 5.0.4 on 2024-05-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(),
        ),
    ]
