# Generated by Django 5.0.4 on 2024-05-14 16:31

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_recipeingredients_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=50, null=True, validators=[recipes.validators.vlidation_unit_measure]),
        ),
    ]
